### ISSUE TITLE
Vibrancy mixin with fallback color for Firefox which doesn't support backdrop-filter blur

### ISSUE THREAD

**Issue by SRFeesha** [wonderflow-bv/wanda#170]
## Problem
On firefox, the blur effect provided by the `vibrancy` mixins is not rendered — the end result is a transparent background. 
The intended design is (often) an opaque color (sometimes it also poses a legibility problem).

### Example
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/37656925/172339634-2a252c81-85ab-441a-8f31-353b5f91526e.png">

---

## Proposed solution
Is it possible to add a fallback with `@supports` for the backdrop filter directly in [wanda’s vibrancy mixin](https://github.com/wonderflow-bv/wanda/blob/fd38b9aee3208041122276910e7ba616050152d8/packages/react-components/src/core/utils/vibrancy.css)?

``` CSS
@define-mixin vibrancy $fallback-color {

  @supports (backdrop-filter: none) {
    backdrop-filter: saturate(180%) blur(62px);
  }
  @supports not (backdrop-filter: none) {
    background-color: var(--global-background);
    background-color: $fallback-color;
  }
}
```

### Considerations
1. Fallback color won't be always the same. We could support a default fallback color (`global-background`?), but also make it easy to override it with the proper color 
2. `token()` doesn't work inside mixin variables: we can't do stuff like `background-color: hsl(token(--color-support-white / 90%));` (which will be maybe similar to the intended result)
3. What's the added value of adding this 'automation' when the consumer has, most of the time, to manually specify the fallback color? Is the default fallback color really an improvement, or this could be managed inside custom rules for the component, instead of cluttering the mixin?

**Comment by SRFeesha** [comment]
Another fallback approach could leverage `@mixin-content`. The main advantage of this approach is that it supports both the `var()` and the `token()` approach

```CSS
/* vibrancy.css */
@define-mixin vibrancy $fallback-color {

  @supports (backdrop-filter: none) {
    backdrop-filter: saturate(180%) blur(62px);
  }
  @supports not (backdrop-filter: none) {
    background-color: var(--global-background);
    @mixin-content;
  }
}
```

```CSS
/* <consumer file>.css */
@mixin vibrancy {
  background-color: hsl(token(--color-support-brand) / 90%);
}
```
